---
title: "Visual Analytics"
author: "Christian Urcuqui"
date: "27 February 2018"
github: "urcuqui"
webpage: "urcuqui.github.com"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries

```{r libraries, include=FALSE}

# librerias para instalar
# install.packages("tidyverse")
# install.packages("openair")
# install.packages("quantmod")
# install.packages("readxl")
# install.packages("lubridate")
# install.packages("treemap")

library(tidyverse)
library(openair) #Libreria para calendar plots  
library(quantmod) # This library allows for an easy way to get daily stock data
library(readxl)
library(lubridate)
library(treemap)


```

## Ejercicio 1

```{r first, echo=FALSE}

#diapositivas 24-27
?mpg
str(mpg)

ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy)) +
  xlab("tamano del motor") +
  ylab("eficiencia del carro en carretera")

ggplot (data = mpg) + 
  geom_point(mapping =aes(x=hwy, y=cyl))

ggplot (data = mpg) + 
  geom_point(mapping =aes(x=class, y=drv))

# Aesthehic Mappings
# diapositivas 30 -34

ggplot(data=mpg) + 
  geom_point(mapping=aes(x=displ, y=hwy, color=class))

ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy, size=class))

ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy, alpha=class))

ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy, shape=class))

ggplot(data=mpg) + 
  geom_point(mapping=aes(x=displ, y=hwy), color="blue")

?geom_point

ggplot(data=mpg) + 
  geom_point(mapping=aes(x=displ, y=hwy, color="blue"))

```

## Facets

```{r other_Data, echo=FALSE}

#diapositivas  36-38
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_wrap(~ class, nrow=2)

ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_wrap(drv ~ cyl) 

ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_grid(. ~ cyl) 


```
## Ejercicio 2


```{r facetsother, echo=FALSE}
#diapositivas 39-40

#1
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_grid(~displ)

#2
ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_grid(drv ~ cyl)

ggplot(data=mpg) +
  geom_point(mapping=aes(x=drv, y=cyl))

#3
ggplot(data=mpg) +
  geom_point(mapping = aes(x =  displ, y=hwy)) +
  facet_grid(drv ~.)

ggplot(data=mpg) +
  geom_point(mapping=aes(x=displ, y=hwy)) +
  facet_grid(. ~ cyl) 

#4
ggplot(data =mpg) +
  geom_point(mapping=aes(x = displ, y=hwy)) +
  facet_wrap(~class, nrow=2)

#5
ggplot(data =mpg) +
  geom_point(mapping=aes(x = displ, y=hwy)) +
  facet_wrap(~class, ncol =2)


```

## Objetos geometricos

```{r geometric, echo=FALSE}
#diapositivas 43-45

ggplot(data=mpg) +
  geom_point(mapping = aes(x =displ, y=hwy))

ggplot(data=mpg) +
  geom_smooth(mapping = aes(x =displ, y=hwy, linetype=drv))

ggplot(data=mpg) +
  geom_smooth(mapping = aes(x =displ, y=hwy, linetype=drv, colour=drv))+
  geom_point(mapping = aes(x =displ, y=hwy, colour=drv))

ggplot(data = mpg) +
  geom_smooth(mapping=aes(x=displ, y=hwy))

ggplot(data = mpg) +
  geom_smooth(mapping=aes(x=displ, y=hwy, group=drv))

ggplot(data = mpg) +
  geom_smooth(mapping=aes(x=displ, y=hwy, group=drv, color=drv),
              show.legend = FALSE)

ggplot(data=mpg, mapping=aes(x =displ, y=hwy)) +
  geom_point(mapping = aes(colour=class)) +
  geom_smooth()

```


## grafico de barras
 

```{r barGraph, echo=FALSE}
#diapositivas 47-48

str(diamonds)

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x=cut))

#stat count is the default setting in geom_bar, so if we change it to the another one we will get the same result
ggplot(data = diamonds) +
  stat_count(mapping = aes(x=cut))

ggplot(data=diamonds) +
  stat_summary(
    mapping = aes(x=cut, y=depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )



```

## Ejercicio 3

```{r exer3, echo=FALSE}

#diapositivas 
ggplot(data=diamonds) +
  geom_histogram(mapping = aes(x=carat))

#2. what is the difference between geom_bar and geom_col
ggplot(data=diamonds) +
  geom_bar(mapping = aes(x=cut))

ggplot(data=diamonds) +
  geom_col(mapping = aes(cut,table))

# geom_col allows us to define the heights of the bars 

```
Let's see more bar charts with colors!


```{r bar2, echo=FALSE}
# diapositivas 50-54
ggplot(data=diamonds) + 
geom_bar(mapping=aes(x=cut, colour=cut))

ggplot(data=diamonds) + 
geom_bar(mapping=aes(x=cut, fill=cut))

ggplot(data=diamonds) + 
geom_bar(mapping=aes(x=cut, fill=clarity))

#what happen if we use position identity in the previous plot
ggplot(data=diamonds) + 
geom_bar(mapping=aes(x=cut, fill=clarity), position="identity")
# the previous plot is not fine because some charts are overlapped, so, we need to change some aesthetic parameters
ggplot(data=diamonds,
mapping=aes(x=cut, fill=clarity)) + 
geom_bar(alpha=1/5, position="identity") 


```

# Geom Line y ejercicio 4

```{r line, echo=FALSE}
# diapositivas 56-57
# Load the day.csv from the downloaded Bike sharing system project
daily_data = read.csv(file.choose(), header=TRUE, stringsAsFactors = FALSE)

str(daily_data)

daily_data$Date = as.Date(daily_data$dteday)

ggplot(daily_data, aes(Date, cnt)) +
geom_line() +
scale_x_date("month") +
ylab("total de bicletas alquiladas") +
xlab("mes")


```


## histogram

``` {r histogram, hecho=FALSE}

#diapositiva 58
ggplot(data = mpg, aes(cty)) +
  geom_histogram() +
  xlab("millas por galon en ciudad")


```
## box plot

``` {r box, hecho=FALSE}

#diapositiva 59

ggplot(data = mpg, aes(class, hwy)) +
  geom_boxplot() +
  xlab("tipo de carro") +
  ylab("millas por galon") 

ggplot(data = mpg, aes(class, hwy)) +
  geom_boxplot() +
  xlab("tipo de carro") +
  ylab("millas por galon") +
  coord_flip()
 





```
## Treemap

``` {r treemap, hecho=FALSE}
#diapositivas 60-64

summary(mpg)
mpg2008 <- subset(mpg, mpg$year == 2008)

head(mpg2008, 3)

treemap <- treemap(mpg2008, c("class","manufacturer"), vSize="hwy", vColor="cty", 
fontsize.labels = 20, fontsize.title = 42)

?RColorBrewer

treemapHwy <- treemap(mpg2008, c("class", "manufacturer", "model"), vSize= "hwy", vColor="displ", palette ="Oranges", fontsize.labels = 15, fontsize.title = 25)
```


## Calendar plots

``` {r calendar, hecho=FALSE}
#diapositiva 65-69

#Primer ejemplo
getSymbols("QQQ",auto.assign = TRUE) 
data <- as.data.frame(QQQ)
data$returns <- with(data, (QQQ.Close/QQQ.Open-1)*100)
data$date <- as.Date(rownames(data))

calendarPlot(data, pollutant="returns", year=2017,
             cols=c("darkred", "red", "gray", "green", "darkgreen"),
             main="Retornos QQQ % (2017)")

calendarPlot(data, pollutant="returns", year=2018,
             cols=c("darkred", "red", "gray", "green", "darkgreen"),
             main="Retornos QQQ % (2018)")

calendarPlot(data, pollutant="returns", year=2018,
             cols="heat",
             main="Retornos QQQ % (2018)")

#segundo ejemplo
#datos<-read_xlsx("Online Retail.xlsx")
datos<-read_xlsx(file.choose())

datos<-as.data.frame(datos)
head(datos)
table(datos$Country)
datos<-subset(datos, Country=="Germany")

extractdate <- function(date) {
day <- format(date, format="%d")
month <- format(date, format="%m")
year <- format(date, format="%Y")

cbind(day, month, year)
}

datos<-cbind(datos,extractdate(datos$InvoiceDate))
datos[,c(9:11)]<-sapply(datos[,c(9:11)],as.character)

datosagg<-aggregate(Quantity ~ year+month+day, data= datos,sum, na.action=NULL)
datosagg$fecha<-paste0(datosagg$year,datosagg$month,datosagg$day)
datosagg$date<-as.Date(datosagg$fecha,format="%Y%m%d")

calendarPlot(datosagg, pollutant="Quantity", year=2010,
cols="heat",
main="Env??os a Alemania (2010)")

calendarPlot(datosagg, pollutant="Quantity", year=2011,
cols="heat",
main="Env??os a Alemania (2011)")
```